version: 2.1
jobs:
  build:

    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: zip -r banking-api.zip .


  deploy-job:
    docker:
      - image: circleci/node:4.8.2 # the primary container
    steps:
      - add_ssh_keys:
          fingerprints:
            - "02:c3:28:23:ba:97:f0:dd:d4:3a:55:9f:d3:cf:c4:03"
      - run:
          name: Deploy over SSH
          command: |
            ssh -i banking-api.pem ec2-user@54.221.22.212 "scp -i banking-api.pem banking-api.zip ec2-user@54.221.22.212:/home/ec2-user"

#      - run: scp -i banking-api.pem banking-api.zip ec2-user@54.221.22.212:/home/ec2-user
#      - run: ssh -i banking-api.pem ec2-user@54.221.22.212
      - run: unzip banking-api.zip
      - run: cd banking-api
      - run: npm i
      - run: npm start


workflows:
  version: 2.1

  my_workflow:
    jobs:
      - build
      - deploy-job





