version: 2.1
jobs:
  build:

    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Show Directory
          command: pwd
      # there's a zip, we need to pass it between jobs
      - run: zip -r banking-api.zip .
      # https://circleci.com/docs/2.0/configuration-reference/#persist_to_workspace
      # persist file in workspace
      - persist_to_workspace:
          root: ./
          paths:
            - banking-api.zip

  deploy-job:
    docker:
      - image: circleci/node:4.8.2 # the primary container
    steps:
      - add_ssh_keys:
          fingerprints:
            - "02:c3:28:23:ba:97:f0:dd:d4:3a:55:9f:d3:cf:c4:03"
      - run:
          name: Show Directory
          command: ls
      - run:
          name: Deploy over SSH
          command: |
            scp banking-api.zip $SSH_USER@$SSH_HOST:/home/$SSH_USER

      - run: unzip banking-api.zip
      - run: cd banking-api
      - run: npm i
      - run: npm start

workflows:
  version: 2.1
  my_workflow:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
