version: 2.1
  jobs:
    build:
      working_directory: ~/tmp
      docker:
          - image: circleci/node:7
      steps:
        - checkout # check out the code in the project directory
        - run: npm install # run the `echo` command
        - run: npm test